### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by MikeMcC399**
Cypress to 9.7.0
actions/checkout to v3
actions/cache to v3

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@bahmutov 

There haven't been any updates here for the last 3 years. Are you still going to maintain this repository?

This PR just updates the core dependencies so the workflow doesn't produce deprecation warnings.

**Comment by bahmutov** [comment]
;) I update the repos as I see a need. Sent from my iPhoneOn Feb 20, 2023, at 11:20, Mike McCready ***@***.***> wrote:﻿
@bahmutov
There haven't been any updates here for the last 3 years. Are you still going to maintain this repository?
This PR just updates the core dependencies so the workflow doesn't produce deprecation warnings.

**Comment by MikeMcC399** [comment]
@bahmutov

> ;) I update the repos as I see a need.

I am working on updating the [cypress-io/github-action](https://github.com/cypress-io/github-action) repo, especially the documentation and examples.

Since

https://github.com/cypress-io/github-action#custom-install
https://github.com/cypress-io/github-action#more-examples

link to this repository I was interested to get this repository updated, so at least if an interested user forks it and runs the workflow they would not get deprecation warnings. If the dependencies are not updated, as in this PR, then the workflow will stop being useable later this year as GitHub makes changes.

Your answer was not clear about whether you see a need or not and therefore whether you will update. If you do not intend to update, then I will close this PR.

**Comment by MikeMcC399** [comment]
Since there was no further response, now closing.

**Pull request closed without merging**
